#spring.application.name=ckdp
server:
  port: 8080

spring:
  application:
    name: ckdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ckdp
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 1
mybatis:
  mapperLocations: classpath:mapper/*.xml
rocketmq:
  name-server: 192.168.112.129:9876
  producer:
    group: ckdp-producer
  consumer:
    group: ckdp-consumer


springdoc:
  api-docs:
    enabled: true
    path: /api/docs # 默认/v3/api-docs
  swagger-ui:
    path: /api/ui #自定义swagger-ui HTML文档路径